package org.djunits.value.vdouble.vector;

import java.util.List;
import java.util.SortedMap;

import org.djunits.unit.Unit;
import org.djunits.value.Absolute;
import org.djunits.value.DenseData;
import org.djunits.value.Relative;
import org.djunits.value.SparseData;
import org.djunits.value.ValueException;
import org.djunits.value.ValueUtil;
import org.djunits.value.vdouble.DoubleFunction;
import org.djunits.value.vdouble.DoubleMathFunctions;
import org.djunits.value.vdouble.DoubleMathFunctionsImpl;
import org.djunits.value.vdouble.scalar.DoubleScalar;

/**
 * MutableDoubleVector.
 * <p>
 * This file was generated by the djunits value classes generator, 26 jun, 2015
 * <p>
 * Copyright (c) 2015 Delft University of Technology, PO Box 5, 2600 AA, Delft, the Netherlands. All rights reserved. <br>
 * BSD-style license. See <a href="http://djunits.org/docs/license.html">DJUNITS License</a>.
 * <p>
 * $LastChangedDate$, @version $Revision$, by $Author$, initial
 * version 30 Oct, 2015 <br>
 * @author <a href="http://www.tbm.tudelft.nl/averbraeck">Alexander Verbraeck</a>
 * @author <a href="http://www.tudelft.nl/pknoppers">Peter Knoppers</a>
 * @param <U> Unit; the unit of this MutableDoubleVector
 */
public abstract class MutableDoubleVector<U extends Unit<U>> extends DoubleVector<U> implements
    WriteDoubleVectorFunctions<U>, DoubleMathFunctions<MutableDoubleVector<U>>
{
    /**  */
    private static final long serialVersionUID = 20151003L;

    /**
     * Construct a new MutableDoubleVector.
     * @param unit U; the unit of the new MutableDoubleVector
     */
    protected MutableDoubleVector(final U unit)
    {
        super(unit);
    }

    /** If set, any modification of the data must be preceded by replacing the data with a local copy. */
    private boolean copyOnWrite = false;

    /**
     * Retrieve the value of the copyOnWrite flag.
     * @return boolean
     */
    private boolean isCopyOnWrite()
    {
        return this.copyOnWrite;
    }

    /**
     * Change the copyOnWrite flag.
     * @param copyOnWrite boolean; the new value for the copyOnWrite flag
     */
    final void setCopyOnWrite(final boolean copyOnWrite)
    {
        this.copyOnWrite = copyOnWrite;
    }

    /** ============================================================================================ */
    /** ================================= ABSOLUTE IMPLEMENTATION ================================== */
    /** ============================================================================================ */

    /**
     * @param <U> Unit the unit for which this Vector will be created
     */
    public abstract static class Abs<U extends Unit<U>> extends MutableDoubleVector<U> implements Absolute
    {
        /**  */
        private static final long serialVersionUID = 20151003L;

        /**
         * Construct a new Absolute MutableDoubleVector.
         * @param unit U; the unit of the new Absolute MutableDoubleVector
         */
        protected Abs(final U unit)
        {
            super(unit);
        }

        /**
         * ABSOLUTE DENSE implementation of MutableDoubleVector.
         * @param <U> Unit the unit for which this Vector will be created
         */
        public static class Dense<U extends Unit<U>> extends Abs<U> implements DenseData
        {
            /** */
            private static final long serialVersionUID = 20151003L;

            /**
             * Construct a new Absolute Dense Mutable DoubleVector.
             * @param values double[]; the values of the entries in the new Absolute Dense Mutable DoubleVector
             * @param unit U; the unit of the new Absolute Dense MutableDoubleVector
             * @throws ValueException when values is null
             */
            public Dense(final double[] values, final U unit) throws ValueException
            {
                super(unit);
                this.data = initializeDense(values);
            }

            /**
             * Construct a new Absolute Dense Mutable DoubleVector.
             * @param values List; the values of the entries in the new Absolute Dense Mutable DoubleVector
             * @param unit U; the unit of the new Absolute Dense Mutable DoubleVector
             * @throws ValueException when values is null
             */
            public Dense(final List<Double> values, final U unit) throws ValueException
            {
                super(unit);
                this.data = initializeDense(values);
            }

            /**
             * Construct a new Absolute Dense Mutable DoubleVector.
             * @param values DoubleScalar.Abs&lt;U&gt;[]; the values of the entries in the new Absolute Dense
             *            MutableDoubleVector
             * @throws ValueException when values has zero entries
             */
            public Dense(final DoubleScalar.Abs<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                this.data = initializeDense(values);
            }

            /**
             * Construct a new Absolute Dense Mutable DoubleVector.
             * @param values List; the values of the entries in the new Absolute Dense Mutable DoubleVector
             * @throws ValueException when values has zero entries
             */
            public Dense(final List<DoubleScalar.Abs<U>> values) throws ValueException
            {
                super(checkNonEmptyLA(values).get(0).getUnit());
                this.data = initializeDenseLA(values);
            }

            /**
             * Construct a new Absolute Dense Mutable DoubleVector.
             * @param data an internal data object
             * @param unit the unit
             */
            Dense(final DoubleVectorDataDense data, final U unit)
            {
                super(unit);
                this.data = data.copy();
            }

            /** {@inheritDoc} */
            @Override
            public final DoubleVector.Abs.Dense<U> immutable()
            {
                setCopyOnWrite(true);
                return new DoubleVector.Abs.Dense<U>(getData(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Abs.Dense<U> mutable()
            {
                setCopyOnWrite(true);
                final MutableDoubleVector.Abs.Dense<U> result =
                    new MutableDoubleVector.Abs.Dense<U>(getData(), getUnit());
                result.setCopyOnWrite(true);
                return result;
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Abs.Dense<U> copy()
            {
                return mutable();
            }

            /** {@inheritDoc} */
            @Override
            protected final DoubleVectorDataDense getData()
            {
                return (DoubleVectorDataDense) this.data;
            }
        }

        /**
         * ABSOLUTE SPARSE implementation of MutableDoubleVector.
         * @param <U> Unit the unit for which this Vector will be created
         */
        public static class Sparse<U extends Unit<U>> extends Abs<U> implements SparseData
        {
            /**  */
            private static final long serialVersionUID = 20151003L;

            /**
             * Construct a new Absolute Sparse Mutable DoubleVector.
             * @param values Map; the map of indexes to values of the Absolute Sparse Mutable DoubleVector
             * @param unit U; the unit of the new Absolute Sparse Mutable DoubleVector
             * @param length the size of the vector
             * @throws ValueException when values is null
             */
            public Sparse(final SortedMap<Integer, Double> values, final U unit, final int length)
                throws ValueException
            {
                super(unit);
                this.data = initializeSparse(values, length);
            }

            /**
             * Construct a new Absolute Sparse Mutable DoubleVector.
             * @param values DoubleScalar.Abs&lt;U&gt;[]; the values of the entries in the new Absolute Sparse Mutable
             *            DoubleVector
             * @param length the size of the vector
             * @throws ValueException when values has zero entries
             */
            public Sparse(final SortedMap<Integer, DoubleScalar.Abs<U>> values, final int length) throws ValueException
            {
                super(checkNonEmptyMA(values).get(0).getUnit());
                initializeSparseMA(values, length);
            }

            /**
             * Construct a new Absolute Sparse Mutable DoubleVector.
             * @param values double[]; the values of the entries in the new Absolute Sparse Mutable DoubleVector
             * @param unit U; the unit of the new Absolute Sparse Mutable DoubleVector
             * @throws ValueException when values is null
             */
            public Sparse(final double[] values, final U unit) throws ValueException
            {
                super(unit);
                this.data = initializeDense(values).toSparse();
            }

            /**
             * Construct a new Absolute Sparse Mutable DoubleVector.
             * @param values DoubleScalar.Abs&lt;U&gt;[]; the values of the entries in the new Absolute Sparse Mutable
             *            DoubleVector
             * @throws ValueException when values has zero entries
             */
            public Sparse(final DoubleScalar.Abs<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                this.data = initializeDense(values).toSparse();
            }

            /**
             * Construct a new Absolute Sparse Mutable DoubleVector, package method.
             * @param data the sparse data (internal structure)
             * @param unit U; the unit of the new Absolute Sparse Mutable DoubleVector
             */
            Sparse(final DoubleVectorDataSparse data, final U unit)
            {
                super(unit);
                this.data = data.copy();
            }

            /** {@inheritDoc} */
            @Override
            public final DoubleVector.Abs.Sparse<U> immutable()
            {
                setCopyOnWrite(true);
                return new DoubleVector.Abs.Sparse<U>(getData(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Abs.Sparse<U> mutable()
            {
                setCopyOnWrite(true);
                final MutableDoubleVector.Abs.Sparse<U> result =
                    new MutableDoubleVector.Abs.Sparse<U>(getData(), getUnit());
                result.setCopyOnWrite(true);
                return result;
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Abs.Sparse<U> copy()
            {
                return mutable();
            }

            /** {@inheritDoc} */
            @Override
            protected final DoubleVectorDataSparse getData()
            {
                return (DoubleVectorDataSparse) this.data;
            }
        }

        /** ================================= ABS GENERAL METHODS ================================== */

        /** {@inheritDoc} */
        @Override
        public final DoubleScalar.Abs<U> get(final int index) throws ValueException
        {
            return new DoubleScalar.Abs<U>(getInUnit(index, getUnit()), getUnit());
        }

        /**
         * Increment the value by the supplied value and return the result.
         * @param increment DoubleVector.Rel&lt;U&gt;; amount by which the value is incremented
         * @return MutableDoubleVector.Abs&lt;U&gt;
         * @throws ValueException when the size of increment is not identical to the size of this
         */
        public final MutableDoubleVector.Abs<U> incrementBy(final DoubleVector.Rel<U> increment) throws ValueException
        {
            return (MutableDoubleVector.Abs<U>) incrementByImpl(increment);
        }

        /**
         * Decrement the value by the supplied value and return the result.
         * @param decrement DoubleVector.Rel&lt;U&gt;; amount by which the value is decremented
         * @return MutableDoubleVector.Abs&lt;U&gt;
         * @throws ValueException when the size of increment is not identical to the size of this
         */
        public final MutableDoubleVector.Abs<U> decrementBy(final DoubleVector.Rel<U> decrement) throws ValueException
        {
            return (MutableDoubleVector.Abs<U>) decrementByImpl(decrement);
        }

        /**********************************************************************************/
        /********************************** MATH METHODS **********************************/
        /**********************************************************************************/

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> abs()
        {
            assign(DoubleMathFunctionsImpl.ABS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> acos()
        {
            assign(DoubleMathFunctionsImpl.ACOS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> asin()
        {
            assign(DoubleMathFunctionsImpl.ASIN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> atan()
        {
            assign(DoubleMathFunctionsImpl.ATAN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> cbrt()
        {
            assign(DoubleMathFunctionsImpl.CBRT);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> ceil()
        {
            assign(DoubleMathFunctionsImpl.CEIL);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> cos()
        {
            assign(DoubleMathFunctionsImpl.COS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> cosh()
        {
            assign(DoubleMathFunctionsImpl.COSH);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> exp()
        {
            assign(DoubleMathFunctionsImpl.EXP);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> expm1()
        {
            assign(DoubleMathFunctionsImpl.EXPM1);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> floor()
        {
            assign(DoubleMathFunctionsImpl.FLOOR);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> log()
        {
            assign(DoubleMathFunctionsImpl.LOG);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> log10()
        {
            assign(DoubleMathFunctionsImpl.LOG10);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> log1p()
        {
            assign(DoubleMathFunctionsImpl.LOG1P);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> pow(final double x)
        {
            assign(DoubleMathFunctionsImpl.POW(x));
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> rint()
        {
            assign(DoubleMathFunctionsImpl.RINT);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> round()
        {
            assign(DoubleMathFunctionsImpl.ROUND);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> signum()
        {
            assign(DoubleMathFunctionsImpl.SIGNUM);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> sin()
        {
            assign(DoubleMathFunctionsImpl.SIN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> sinh()
        {
            assign(DoubleMathFunctionsImpl.SINH);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> sqrt()
        {
            assign(DoubleMathFunctionsImpl.SQRT);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> tan()
        {
            assign(DoubleMathFunctionsImpl.TAN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> tanh()
        {
            assign(DoubleMathFunctionsImpl.TANH);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> toDegrees()
        {
            assign(DoubleMathFunctionsImpl.TO_DEGREES);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> toRadians()
        {
            assign(DoubleMathFunctionsImpl.TO_RADIANS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> inv()
        {
            assign(DoubleMathFunctionsImpl.INV);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> multiplyBy(final double constant)
        {
            assign(DoubleMathFunctionsImpl.MULT(constant));
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Abs<U> divideBy(final double constant)
        {
            assign(DoubleMathFunctionsImpl.DIV(constant));
            return this;
        }

    }

    /** ============================================================================================ */
    /** ================================= RELATIVE IMPLEMENTATION ================================== */
    /** ============================================================================================ */

    /**
     * @param <U> Unit the unit for which this Vector will be created
     */
    public abstract static class Rel<U extends Unit<U>> extends MutableDoubleVector<U> implements Relative
    {
        /**  */
        private static final long serialVersionUID = 20151003L;

        /**
         * Construct a new Relative MutableDoubleVector.
         * @param unit U; the unit of the new Relative MutableDoubleVector
         */
        protected Rel(final U unit)
        {
            super(unit);
        }

        /**
         * RELATIVE DENSE implementation of MutableDoubleVector.
         * @param <U> Unit the unit for which this Vector will be created
         */
        public static class Dense<U extends Unit<U>> extends Rel<U> implements DenseData
        {
            /** */
            private static final long serialVersionUID = 20151003L;

            /**
             * Construct a new Relative Dense Mutable DoubleVector.
             * @param values double[]; the values of the entries in the new Relative Dense Mutable DoubleVector
             * @param unit U; the unit of the new Relative Dense MutableDoubleVector
             * @throws ValueException when values is null
             */
            public Dense(final double[] values, final U unit) throws ValueException
            {
                super(unit);
                this.data = initializeDense(values);
            }

            /**
             * Construct a new Relative Dense Mutable DoubleVector.
             * @param values List; the values of the entries in the new Relative Dense Mutable DoubleVector
             * @param unit U; the unit of the new Relative Dense Mutable DoubleVector
             * @throws ValueException when values is null
             */
            public Dense(final List<Double> values, final U unit) throws ValueException
            {
                super(unit);
                this.data = initializeDense(values);
            }

            /**
             * Construct a new Relative Dense Mutable DoubleVector.
             * @param values DoubleScalar.Rel&lt;U&gt;[]; the values of the entries in the new Relative Dense
             *            MutableDoubleVector
             * @throws ValueException when values has zero entries
             */
            public Dense(final DoubleScalar.Rel<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                this.data = initializeDense(values);
            }

            /**
             * Construct a new Relative Dense Mutable DoubleVector.
             * @param values List; the values of the entries in the new Relative Dense Mutable DoubleVector
             * @throws ValueException when values has zero entries
             */
            public Dense(final List<DoubleScalar.Rel<U>> values) throws ValueException
            {
                super(checkNonEmptyLR(values).get(0).getUnit());
                this.data = initializeDenseLR(values);
            }

            /**
             * Construct a new Relative Dense Mutable DoubleVector.
             * @param data an internal data object
             * @param unit the unit
             */
            Dense(final DoubleVectorDataDense data, final U unit)
            {
                super(unit);
                this.data = data.copy();
            }

            /** {@inheritDoc} */
            @Override
            public final DoubleVector.Rel.Dense<U> immutable()
            {
                setCopyOnWrite(true);
                return new DoubleVector.Rel.Dense<U>(getData(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Rel.Dense<U> mutable()
            {
                setCopyOnWrite(true);
                final MutableDoubleVector.Rel.Dense<U> result =
                    new MutableDoubleVector.Rel.Dense<U>(getData(), getUnit());
                result.setCopyOnWrite(true);
                return result;
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Rel.Dense<U> copy()
            {
                return mutable();
            }

            /** {@inheritDoc} */
            @Override
            protected final DoubleVectorDataDense getData()
            {
                return (DoubleVectorDataDense) this.data;
            }
        }

        /**
         * RELATIVE SPARSE implementation of MutableDoubleVector.
         * @param <U> Unit the unit for which this Vector will be created
         */
        public static class Sparse<U extends Unit<U>> extends Rel<U> implements SparseData
        {
            /**  */
            private static final long serialVersionUID = 20151003L;

            /**
             * Construct a new Relative Sparse Mutable DoubleVector.
             * @param values Map; the map of indexes to values of the Relative Sparse Mutable DoubleVector
             * @param unit U; the unit of the new Relative Sparse Mutable DoubleVector
             * @param length the size of the vector
             * @throws ValueException when values is null
             */
            public Sparse(final SortedMap<Integer, Double> values, final U unit, final int length)
                throws ValueException
            {
                super(unit);
                this.data = initializeSparse(values, length);
            }

            /**
             * Construct a new Relative Sparse Mutable DoubleVector.
             * @param values DoubleScalar.Rel&lt;U&gt;[]; the values of the entries in the new Relative Sparse Mutable
             *            DoubleVector
             * @param length the size of the vector
             * @throws ValueException when values has zero entries
             */
            public Sparse(final SortedMap<Integer, DoubleScalar.Rel<U>> values, final int length) throws ValueException
            {
                super(checkNonEmptyMR(values).get(0).getUnit());
                this.data = initializeSparseMR(values, length);
            }

            /**
             * Construct a new Relative Sparse Mutable DoubleVector.
             * @param values double[]; the values of the entries in the new Relative Sparse Mutable DoubleVector
             * @param unit U; the unit of the new Relative Sparse Mutable DoubleVector
             * @throws ValueException when values is null
             */
            public Sparse(final double[] values, final U unit) throws ValueException
            {
                super(unit);
                this.data = initializeDense(values).toSparse();
            }

            /**
             * Construct a new Relative Sparse Mutable DoubleVector.
             * @param values DoubleScalar.Abs&lt;U&gt;[]; the values of the entries in the new Relative Sparse Mutable
             *            DoubleVector
             * @throws ValueException when values has zero entries
             */
            public Sparse(final DoubleScalar.Abs<U>[] values) throws ValueException
            {
                super(checkNonEmpty(values)[0].getUnit());
                this.data = initializeDense(values).toSparse();
            }

            /**
             * Construct a new Relative Sparse Mutable DoubleVector, package method.
             * @param data the sparse data (internal structure)
             * @param unit U; the unit of the new Relative Sparse Mutable DoubleVector
             */
            Sparse(final DoubleVectorDataSparse data, final U unit)
            {
                super(unit);
                this.data = data.copy();
            }

            /** {@inheritDoc} */
            @Override
            public final DoubleVector.Rel.Sparse<U> immutable()
            {
                setCopyOnWrite(true);
                return new DoubleVector.Rel.Sparse<U>(getData(), getUnit());
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Rel.Sparse<U> mutable()
            {
                setCopyOnWrite(true);
                final MutableDoubleVector.Rel.Sparse<U> result =
                    new MutableDoubleVector.Rel.Sparse<U>(getData(), getUnit());
                result.setCopyOnWrite(true);
                return result;
            }

            /** {@inheritDoc} */
            @Override
            public final MutableDoubleVector.Rel.Sparse<U> copy()
            {
                return mutable();
            }

            /** {@inheritDoc} */
            @Override
            protected final DoubleVectorDataSparse getData()
            {
                return (DoubleVectorDataSparse) this.data;
            }
        }

        /** ================================= REL GENERAL METHODS ================================== */

        /** {@inheritDoc} */
        @Override
        public final DoubleScalar.Rel<U> get(final int index) throws ValueException
        {
            return new DoubleScalar.Rel<U>(getInUnit(index, getUnit()), getUnit());
        }

        /**
         * Increment the value by the supplied value and return the result.
         * @param increment DoubleVector.Rel&lt;U&gt;; amount by which the value is incremented
         * @return MutableDoubleVector.Rel&lt;U&gt;
         * @throws ValueException when the size of increment is not identical to the size of this
         */
        public final MutableDoubleVector.Rel<U> incrementBy(final DoubleVector.Rel<U> increment) throws ValueException
        {
            return (MutableDoubleVector.Rel<U>) incrementByImpl(increment);
        }

        /**
         * Decrement the value by the supplied value and return the result.
         * @param decrement DoubleVector.Rel&lt;U&gt;; amount by which the value is decremented
         * @return MutableDoubleVector.Rel&lt;U&gt;
         * @throws ValueException when the size of increment is not identical to the size of this
         */
        public final MutableDoubleVector.Rel<U> decrementBy(final DoubleVector.Rel<U> decrement) throws ValueException
        {
            return (MutableDoubleVector.Rel<U>) decrementByImpl(decrement);
        }

        /**********************************************************************************/
        /********************************** MATH METHODS **********************************/
        /**********************************************************************************/

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> abs()
        {
            assign(DoubleMathFunctionsImpl.ABS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> acos()
        {
            assign(DoubleMathFunctionsImpl.ACOS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> asin()
        {
            assign(DoubleMathFunctionsImpl.ASIN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> atan()
        {
            assign(DoubleMathFunctionsImpl.ATAN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> cbrt()
        {
            assign(DoubleMathFunctionsImpl.CBRT);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> ceil()
        {
            assign(DoubleMathFunctionsImpl.CEIL);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> cos()
        {
            assign(DoubleMathFunctionsImpl.COS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> cosh()
        {
            assign(DoubleMathFunctionsImpl.COSH);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> exp()
        {
            assign(DoubleMathFunctionsImpl.EXP);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> expm1()
        {
            assign(DoubleMathFunctionsImpl.EXPM1);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> floor()
        {
            assign(DoubleMathFunctionsImpl.FLOOR);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> log()
        {
            assign(DoubleMathFunctionsImpl.LOG);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> log10()
        {
            assign(DoubleMathFunctionsImpl.LOG10);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> log1p()
        {
            assign(DoubleMathFunctionsImpl.LOG1P);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> pow(final double x)
        {
            assign(DoubleMathFunctionsImpl.POW(x));
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> rint()
        {
            assign(DoubleMathFunctionsImpl.RINT);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> round()
        {
            assign(DoubleMathFunctionsImpl.ROUND);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> signum()
        {
            assign(DoubleMathFunctionsImpl.SIGNUM);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> sin()
        {
            assign(DoubleMathFunctionsImpl.SIN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> sinh()
        {
            assign(DoubleMathFunctionsImpl.SINH);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> sqrt()
        {
            assign(DoubleMathFunctionsImpl.SQRT);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> tan()
        {
            assign(DoubleMathFunctionsImpl.TAN);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> tanh()
        {
            assign(DoubleMathFunctionsImpl.TANH);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> toDegrees()
        {
            assign(DoubleMathFunctionsImpl.TO_DEGREES);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> toRadians()
        {
            assign(DoubleMathFunctionsImpl.TO_RADIANS);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> inv()
        {
            assign(DoubleMathFunctionsImpl.INV);
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> multiplyBy(final double constant)
        {
            assign(DoubleMathFunctionsImpl.MULT(constant));
            return this;
        }

        /** {@inheritDoc} */
        @Override
        public final MutableDoubleVector.Rel<U> divideBy(final double constant)
        {
            assign(DoubleMathFunctionsImpl.DIV(constant));
            return this;
        }
    }

    /**
     * Make (immutable) DoubleVectorNew equivalent for any type of MutableDoubleVector.
     * @return DoubleVector&lt;U&gt;; immutable version of this DoubleVector
     */
    public abstract DoubleVector<U> immutable();

    /**
     * Check the copyOnWrite flag and, if it is set, make a deep copy of the data and clear the flag.
     */
    protected final void checkCopyOnWrite()
    {
        if (isCopyOnWrite())
        {
            this.data = this.data.copy();
            setCopyOnWrite(false);
        }
    }

    /** {@inheritDoc} */
    @Override
    public final void setSI(final int index, final double valueSI) throws ValueException
    {
        checkIndex(index);
        checkCopyOnWrite();
        safeSet(index, valueSI);
    }

    /** {@inheritDoc} */
    @Override
    public final void set(final int index, final DoubleScalar<U> value) throws ValueException
    {
        setSI(index, value.getSI());
    }

    /** {@inheritDoc} */
    @Override
    public final void setInUnit(final int index, final double value, final U valueUnit) throws ValueException
    {
        setSI(index, ValueUtil.expressAsSIUnit(value, valueUnit));
    }

    /**
     * Execute a function on a cell by cell basis. Note: because many functions have to act on zero cells or can generate cells
     * with a zero value, the functions have to be applied on a dense dataset which has to be transformed back to a dense
     * dataset if necessary.
     * @param doubleFunction the function to apply
     */
    public final void assign(final DoubleFunction doubleFunction)
    {
        checkCopyOnWrite();
        if (this.data instanceof DoubleVectorDataDense)
        {
            ((DoubleVectorDataDense) this.data).assign(doubleFunction);
        }
        else
        {
            DoubleVectorDataDense dvdd = ((DoubleVectorDataSparse) this.data).toDense();
            dvdd.assign(doubleFunction);
            this.data = dvdd.toSparse();
        }
    }

    /**********************************************************************************/
    /******************************* NON-STATIC METHODS *******************************/
    /**********************************************************************************/

    /**
     * Increment the values in this MutableDoubleVector by the corresponding values in a DoubleVector.
     * @param increment DoubleVector&lt;U&gt;; the values by which to increment the corresponding values in this
     *            MutableDoubleVector
     * @return MutableDoubleVector&lt;U&gt;; this modified MutableDoubleVector
     * @throws ValueException when the vectors do not have the same size
     */
    private MutableDoubleVector<U> incrementValueByValue(final DoubleVector<U> increment) throws ValueException
    {
        checkSizeAndCopyOnWrite(increment);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) + increment.safeGet(index));
        }
        return this;
    }

    /**
     * Decrement the values in this MutableDoubleVector by the corresponding values in a DoubleVector.
     * @param decrement DoubleVector&lt;U&gt;; the values by which to decrement the corresponding values in this
     *            MutableDoubleVector
     * @return MutableDoubleVector&lt;U&gt;; this modified MutableDoubleVector
     * @throws ValueException when the vectors do not have the same size
     */
    private MutableDoubleVector<U> decrementValueByValue(final DoubleVector<U> decrement) throws ValueException
    {
        checkSizeAndCopyOnWrite(decrement);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) - decrement.safeGet(index));
        }
        return this;
    }

    /**
     * Increment the values in this MutableDoubleVector by the corresponding values in a Relative DoubleVector. <br>
     * Only Relative values are allowed; adding an Absolute value to an Absolute value is not allowed. Adding an Absolute value
     * to an existing Relative value would require the result to become Absolute, which is a type change that is impossible. For
     * that operation use a static method.
     * @param rel DoubleVector.Rel&lt;U&gt;; the Relative DoubleVector
     * @return MutableDoubleVector&lt;U&gt;; this modified MutableDoubleVector
     * @throws ValueException when the vectors do not have the same size
     */
    protected final MutableDoubleVector<U> incrementByImpl(final DoubleVector.Rel<U> rel) throws ValueException
    {
        return incrementValueByValue(rel);
    }

    /**
     * Decrement the corresponding values of this Relative DoubleVector from the values of this MutableDoubleVector. <br>
     * Only Relative values are allowed; subtracting an Absolute value from a Relative value is not allowed. Subtracting an
     * Absolute value from an existing Absolute value would require the result to become Relative, which is a type change that
     * is impossible. For that operation use a static method.
     * @param rel DoubleVector.Rel&lt;U&gt;; the Relative DoubleVector
     * @return MutableDoubleVector&lt;U&gt;; this modified MutableDoubleVector
     * @throws ValueException when the vectors do not have the same size
     */
    protected final MutableDoubleVector<U> decrementByImpl(final DoubleVector.Rel<U> rel) throws ValueException
    {
        return decrementValueByValue(rel);
    }

    /**
     * Scale the values in this MutableDoubleVector by the corresponding values in a DoubleVector.
     * @param factor DoubleVector&lt;?&gt;; contains the values by which to scale the corresponding values in this
     *            MutableDoubleVector
     * @throws ValueException when the vectors do not have the same size
     */
    protected final void scaleValueByValue(final DoubleVector<?> factor) throws ValueException
    {
        checkSizeAndCopyOnWrite(factor);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) * factor.safeGet(index));
        }
    }

    /**
     * Scale the values in this MutableDoubleVector by the corresponding values in a double array.
     * @param factor double[]; contains the values by which to scale the corresponding values in this MutableDoubleVector
     * @return MutableDoubleVector&lt;U&gt;; this modified MutableDoubleVector
     * @throws ValueException when the vector and the array do not have the same size
     */
    protected final MutableDoubleVector<U> scaleValueByValue(final double[] factor) throws ValueException
    {
        checkSizeAndCopyOnWrite(factor);
        for (int index = size(); --index >= 0;)
        {
            safeSet(index, safeGet(index) * factor[index]);
        }
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public final void normalize() throws ValueException
    {
        double sum = zSum();
        if (0 == sum)
        {
            throw new ValueException("zSum is 0; cannot normalize");
        }
        checkCopyOnWrite();
        for (int i = 0; i < size(); i++)
        {
            // TODO parallel divide by factor
            safeSet(i, safeGet(i) / sum);
        }
    }

    /**
     * Check sizes and copy the data if the copyOnWrite flag is set.
     * @param other DoubleVector&lt;?&gt;; partner for the size check
     * @throws ValueException when the vectors do not have the same size
     */
    private void checkSizeAndCopyOnWrite(final DoubleVector<?> other) throws ValueException
    {
        checkSize(other);
        checkCopyOnWrite();
    }

    /**
     * Check sizes and copy the data if the copyOnWrite flag is set.
     * @param other double[]; partner for the size check
     * @throws ValueException when the vectors do not have the same size
     */
    private void checkSizeAndCopyOnWrite(final double[] other) throws ValueException
    {
        checkSize(other);
        checkCopyOnWrite();
    }

}
