package org.djunits.value.vfloat.vector;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.djunits.unit.LengthUnit;
import org.djunits.unit.TemperatureUnit;
import org.djunits.unit.Unit;
import org.djunits.value.StorageType;
import org.djunits.value.ValueException;
import org.djunits.value.vfloat.scalar.FloatScalar;
import org.junit.Test;

/**
 * Test the FloatVector class.
 * <p>
 * This file was generated by the djunits value test classes generator, 26 jun, 2015
 * <p>
 * Copyright (c) 2015-2016 Delft University of Technology, PO Box 5, 2600 AA, Delft, the Netherlands. All rights reserved. <br>
 * BSD-style license. See <a href="http://djunits.org/docs/license.html">DJUNITS License</a>.
 * <p>
 * $LastChangedDate$, @version $Revision$, by $Author$,
 * initial version 26 jun, 2015 <br>
 * @author <a href="http://www.tbm.tudelft.nl/averbraeck">Alexander Verbraeck</a>
 * @author <a href="http://www.tudelft.nl/pknoppers">Peter Knoppers</a>
 */
public class FloatVectorSparseTest
{
    /**
     * Generate test data.
     * @param size int; number of values in the result
     * @param startValue float; seed value
     * @return float[]
     */
    private static float[] data(final int size, final float startValue)
    {
        float[] result = new float[size];
        for (int index = 0; index < size; index++)
        {
            result[index] = index + startValue;
        }
        return result;
    }

    /**
     * Check that the values in a FloatVectormatch the expected values.
     * @param dv FloatVector&lt;?&gt;; the FloatVector to match
     * @param reference float[]; the reference values
     * @param precision double; the maximum allowed error
     * @param u Unit&lt;?&gt;; the expected type
     * @param expectAbsolute boolean; if true; dv should be Absolute; if false; dv should be Relative
     */
    private static void checkContentsAndType(final AbstractFloatVector<?, ?> dv, final float[] reference, final double precision,
        final Unit<?> u, final boolean expectAbsolute)
    {
        assertTrue("FloatVector should not be null", null != dv);
        for (int index = dv.size(); --index >= 0;)
        {
            try
            {
                assertEquals("Value should match", reference[index], dv.getInUnit(index), precision);
            }
            catch (ValueException exception)
            {
                fail("Unexpected exception");
            }
        }
        assertEquals("Unit should be " + u.toString(), u, dv.getUnit());
        assertTrue("Should be " + (expectAbsolute ? "Absolute" : "Relative"), expectAbsolute ? dv.isAbsolute() : dv
            .isRelative());
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            float[] value = data(3, 38.0f);
            FloatVector.Abs<TemperatureUnit> dv =
                new FloatVector.Abs<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            String result = dv.toString(true, true);
            assertTrue("toString result contains \" Abs \"", result.contains(" Abs "));
            assertTrue("toString result contains \"K\"", result.contains("K"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Immutable"));
            assertTrue("toString contains \"Sparse\"", result.contains("Sparse"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringMutableAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            float[] value = data(3, 38.0f);
            MutableFloatVector.Abs<TemperatureUnit> dv =
                new MutableFloatVector.Abs<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            String result = dv.toString(true, true);
            assertTrue("toString result contains \" Abs \"", result.contains(" Abs "));
            assertTrue("toString result contains \"K\"", result.contains("K"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Mutable"));
            assertTrue("toString contains \"Sparse\"", result.contains("Sparse"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test constructor, verify the various fields in the constructed objects, test conversions to related units.
     */
    @SuppressWarnings({"static-method", "unchecked"})
    @Test
    public final void basicsAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            float[] value = data(3, 38.0f);
            FloatVector.Abs<TemperatureUnit> temperatureDV =
                new FloatVector.Abs<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            checkContentsAndType(temperatureDV, value, 0.001, tempUnit, true);
            assertEquals("Value in SI is equivalent in Kelvin", 311.15, temperatureDV.getSI(0), 0.05);
            assertEquals("Value in Fahrenheit", 100.4, temperatureDV.getInUnit(0, TemperatureUnit.DEGREE_FAHRENHEIT),
                0.1);
            float[] out = temperatureDV.getValuesInUnit();
            for (int index = 0; index < value.length; index++)
            {
                assertEquals("Value should match", value[index], out[index], 0.001);
            }
            MutableFloatVector.Abs<TemperatureUnit> mdv =
                new MutableFloatVector.Abs<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            checkContentsAndType(mdv, value, 0.001, tempUnit, true);
            mdv.setSI(0, 73);
            float safe = value[0];
            value[0] = -200; // Approximate Celsius equivalent of 73 Kelvin
            checkContentsAndType(mdv, value, 1, tempUnit, true);
            value[0] = safe; // Restore
            mdv.set(0, temperatureDV.get(0));
            checkContentsAndType(mdv, value, 0.001, tempUnit, true);
            FloatVector.Abs<TemperatureUnit> temperature2DV =
                new FloatVector.Abs<TemperatureUnit>(temperatureDV.getValuesSI(), TemperatureUnit.KELVIN,
                    StorageType.SPARSE);
            assertTrue("temperature2DV should be equal to temperatureDV", temperature2DV.equals(temperatureDV));
            assertTrue("Value is Absolute", temperatureDV.isAbsolute());
            assertFalse("Value is not Relative", temperatureDV.isRelative());
            temperatureDV = new FloatVector.Abs<TemperatureUnit>(value, TemperatureUnit.KELVIN, StorageType.SPARSE);
            checkContentsAndType(temperatureDV, value, 0.001, TemperatureUnit.KELVIN, true);
            out = temperatureDV.getValuesSI();
            for (int index = 0; index < value.length; index++)
            {
                assertEquals("Value should match", value[index], out[index], 0.001);
            }
            FloatScalar.Abs<TemperatureUnit>[] scalar = new FloatScalar.Abs[value.length];
            for (int index = 0; index < value.length; index++)
            {
                scalar[index] = new FloatScalar.Abs<TemperatureUnit>(value[index], TemperatureUnit.DEGREE_CELSIUS);
            }
            temperatureDV = new FloatVector.Abs<TemperatureUnit>(scalar, StorageType.SPARSE);
            checkContentsAndType(temperatureDV, value, 0.001, tempUnit, true);
            assertEquals("All cells != 0; cardinality should equal number of cells", value.length, temperatureDV
                .cardinality());
            float sum = 0;
            for (int index = 0; index < value.length; index++)
            {
                sum += temperatureDV.getSI(index);
            }
            assertEquals("zSum should be sum of all values", sum, temperatureDV.zSum(), 0.001);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test conversion to mutable equivalent and back.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toMutableAndBackAbsTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            float[] value = data(3, 38.0f);
            float[] value2 = data(3, 38.0f);
            value2[0] = 12345;
            FloatVector.Abs<TemperatureUnit> dv =
                new FloatVector.Abs<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            FloatVector.Abs<TemperatureUnit> dvCopy = dv;
            MutableFloatVector.Abs<TemperatureUnit> mdv = dv.mutable();
            checkContentsAndType(dv, value, 0.001, tempUnit, true);
            checkContentsAndType(mdv, value, 0.001, tempUnit, true);
            checkContentsAndType(dvCopy, value, 0.001, tempUnit, true);
            MutableFloatVector.Abs<TemperatureUnit> mdvCopy = mdv.copy();
            checkContentsAndType(mdvCopy, value, 0.001, tempUnit, true);
            MutableFloatVector.Abs<TemperatureUnit> mmdv = mdv.mutable();
            checkContentsAndType(mmdv, value, 0.001, tempUnit, true);
            assertEquals("hashCode is independent on mutability", dv.hashCode(), mdv.hashCode());
            // Modify mdv
            mdv.setInUnit(0, 12345, TemperatureUnit.DEGREE_CELSIUS);
            checkContentsAndType(dv, value, 0.001, tempUnit, true);
            checkContentsAndType(mdv, value2, 0.01, tempUnit, true);
            checkContentsAndType(mdvCopy, value, 0.001, tempUnit, true);
            checkContentsAndType(mmdv, value, 0.001, tempUnit, true);
            FloatVector.Abs<TemperatureUnit> idv = mdv.immutable();
            assertTrue("Different value extremely likely results in different hashCode", dv.hashCode() != mdv
                .hashCode());
            // Restore value of mdv
            mdv.setSI(0, dv.getSI(0));
            checkContentsAndType(idv, value2, 0.01, tempUnit, true);
            checkContentsAndType(mdv, value, 0.001, tempUnit, true);
            checkContentsAndType(mmdv, value, 0.001, tempUnit, true);
            mmdv.setSI(0, 0);
            checkContentsAndType(mdv, value, 0.001, tempUnit, true);
            assertEquals("value should be about -273", -273, mmdv.getInUnit(0, tempUnit), 0.2);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test the equals method.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void equalsAbsTest()
    {
        LengthUnit lengthUnit = LengthUnit.METER;
        float value = 38.0f;
        FloatScalar.Abs<LengthUnit> dv = new FloatScalar.Abs<LengthUnit>(value, lengthUnit);
        assertTrue("Equal to itself", dv.equals(dv));
        assertFalse("Not equal to null", dv.equals(null));
        assertFalse("Not equal to some other kind of object; e.g. a String", dv.equals(new String("abc")));
        FloatScalar.Rel<LengthUnit> dvCounterPart = new FloatScalar.Rel<LengthUnit>(value, lengthUnit);
        assertFalse("Not equal if one Absolute and other Relative", dv.equals(dvCounterPart));
        FloatScalar.Abs<TemperatureUnit> dvWrongBaseUnit =
            new FloatScalar.Abs<TemperatureUnit>(value, TemperatureUnit.KELVIN);
        assertEquals("The underlying SI values are the same", dv.getSI(), dvWrongBaseUnit.getSI(), 0.0001);
        assertFalse("Not equals because the standard SI unit differs", dv.equals(dvWrongBaseUnit));
        FloatScalar.Abs<LengthUnit> dvCompatibleUnit = new FloatScalar.Abs<LengthUnit>(38000.0f, LengthUnit.MILLIMETER);
        assertFalse("Units are different", dv.getUnit().equals(dvCompatibleUnit.getUnit()));
        assertTrue("equals returns true", dv.equals(dvCompatibleUnit));
        FloatScalar.Abs<LengthUnit> dvDifferentValue = new FloatScalar.Abs<LengthUnit>(123.456f, LengthUnit.MILLIMETER);
        assertFalse("Different value makes equals return false", dv.equals(dvDifferentValue));
    }

    /**
     * Test the Math functions.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void mathFunctionsTestAbsTest()
    {
        float[] seedValues = {-10f, -2f, -1f, -0.5f, -0.1f, 0f, 0.1f, 0.5f, 1f, 2f, 10f};
        for (float seedValue : seedValues)
        {
            float[] input = data(3, seedValue);
            MutableFloatVector.Abs<LengthUnit> dv;
            try
            {
                dv = new MutableFloatVector.Abs<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.ceil();
                MathTester.tester(input, "ceil", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return (float) Math.ceil(d);
                    }
                });
                dv = new MutableFloatVector.Abs<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.floor();
                MathTester.tester(input, "floor", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return (float) Math.floor(d);
                    }
                });
                dv = new MutableFloatVector.Abs<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.rint();
                MathTester.tester(input, "rint", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return (float) Math.rint(d);
                    }
                });
                dv = new MutableFloatVector.Abs<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.round();
                MathTester.tester(input, "round", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return Math.round(d);
                    }
                });
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected ValueException: " + ve.toString());
            }
        }
    }

    /**
     * Test plus(FloatVectorAbs.Sparse, FloatVectorRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfAbsSparseAndRelDenseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Abs<LengthUnit> left =
                new FloatVector.Abs<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Abs<?> result = left.plus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI plus of contributing elements", left.getSI(i)
                    + right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(FloatVectorAbs.Sparse, FloatVectorRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfAbsSparseAndRelDenseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Abs<LengthUnit> left =
                new FloatVector.Abs<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Abs<?> result = left.minus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI minus of contributing elements", left.getSI(i)
                    - right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test plus(FloatVectorAbs.Sparse, FloatVectorRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfAbsSparseAndRelSparseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Abs<LengthUnit> left =
                new FloatVector.Abs<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Abs<?> result = left.plus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI plus of contributing elements", left.getSI(i)
                    + right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(FloatVectorAbs.Sparse, FloatVectorRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfAbsSparseAndRelSparseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Abs<LengthUnit> left =
                new FloatVector.Abs<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Abs<?> result = left.minus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI minus of contributing elements", left.getSI(i)
                    - right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test that malformed or mismatching arrays throw a ValueException.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void sizeCheckAbsTest()
    {
        int junk = 0;
        try
        {
            // null array
            new FloatVector.Abs<TemperatureUnit>((float[]) null, TemperatureUnit.DEGREE_FAHRENHEIT, StorageType.SPARSE);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        assertTrue("The variable junk is only used to suppress annoying warnings of the code checker", junk > 0);
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            float[] value = data(3, 38.0f);
            FloatVector.Rel<TemperatureUnit> dv =
                new FloatVector.Rel<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            String result = dv.toString(true, true);
            assertTrue("toString result contains \" Rel \"", result.contains(" Rel "));
            assertTrue("toString result contains \"K\"", result.contains("K"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Immutable"));
            assertTrue("toString contains \"Sparse\"", result.contains("Sparse"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test that the toString method returns something sensible.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toStringMutableRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.KELVIN;
            float[] value = data(3, 38.0f);
            MutableFloatVector.Rel<TemperatureUnit> dv =
                new MutableFloatVector.Rel<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            String result = dv.toString(true, true);
            assertTrue("toString result contains \" Rel \"", result.contains(" Rel "));
            assertTrue("toString result contains \"K\"", result.contains("K"));
            assertTrue("toString result starts with \"Immutable \"", result.startsWith("Mutable"));
            assertTrue("toString contains \"Sparse\"", result.contains("Sparse"));
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test constructor, verify the various fields in the constructed objects, test conversions to related units.
     */
    @SuppressWarnings({"static-method", "unchecked"})
    @Test
    public final void basicsRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            float[] value = data(3, 38.0f);
            FloatVector.Rel<TemperatureUnit> temperatureDV =
                new FloatVector.Rel<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            checkContentsAndType(temperatureDV, value, 0.001, tempUnit, false);
            assertEquals("Value in SI is equivalent in Kelvin", 311.15, temperatureDV.getSI(0), 0.05);
            assertEquals("Value in Fahrenheit", 100.4, temperatureDV.getInUnit(0, TemperatureUnit.DEGREE_FAHRENHEIT),
                0.1);
            float[] out = temperatureDV.getValuesInUnit();
            for (int index = 0; index < value.length; index++)
            {
                assertEquals("Value should match", value[index], out[index], 0.001);
            }
            MutableFloatVector.Rel<TemperatureUnit> mdv =
                new MutableFloatVector.Rel<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            checkContentsAndType(mdv, value, 0.001, tempUnit, false);
            mdv.setSI(0, 73);
            float safe = value[0];
            value[0] = -200; // Approximate Celsius equivalent of 73 Kelvin
            checkContentsAndType(mdv, value, 1, tempUnit, false);
            value[0] = safe; // Restore
            mdv.set(0, temperatureDV.get(0));
            checkContentsAndType(mdv, value, 0.001, tempUnit, false);
            FloatVector.Rel<TemperatureUnit> temperature2DV =
                new FloatVector.Rel<TemperatureUnit>(temperatureDV.getValuesSI(), TemperatureUnit.KELVIN,
                    StorageType.SPARSE);
            assertTrue("temperature2DV should be equal to temperatureDV", temperature2DV.equals(temperatureDV));
            assertTrue("Value is Relative", temperatureDV.isRelative());
            assertFalse("Value is not Absolute", temperatureDV.isAbsolute());
            temperatureDV = new FloatVector.Rel<TemperatureUnit>(value, TemperatureUnit.KELVIN, StorageType.SPARSE);
            checkContentsAndType(temperatureDV, value, 0.001, TemperatureUnit.KELVIN, false);
            out = temperatureDV.getValuesSI();
            for (int index = 0; index < value.length; index++)
            {
                assertEquals("Value should match", value[index], out[index], 0.001);
            }
            FloatScalar.Rel<TemperatureUnit>[] scalar = new FloatScalar.Rel[value.length];
            for (int index = 0; index < value.length; index++)
            {
                scalar[index] = new FloatScalar.Rel<TemperatureUnit>(value[index], TemperatureUnit.DEGREE_CELSIUS);
            }
            temperatureDV = new FloatVector.Rel<TemperatureUnit>(scalar, StorageType.SPARSE);
            checkContentsAndType(temperatureDV, value, 0.001, tempUnit, false);
            assertEquals("All cells != 0; cardinality should equal number of cells", value.length, temperatureDV
                .cardinality());
            float sum = 0;
            for (int index = 0; index < value.length; index++)
            {
                sum += temperatureDV.getSI(index);
            }
            assertEquals("zSum should be sum of all values", sum, temperatureDV.zSum(), 0.001);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test conversion to mutable equivalent and back.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void toMutableAndBackRelTest()
    {
        try
        {
            TemperatureUnit tempUnit = TemperatureUnit.DEGREE_CELSIUS;
            float[] value = data(3, 38.0f);
            float[] value2 = data(3, 38.0f);
            value2[0] = 12345;
            FloatVector.Rel<TemperatureUnit> dv =
                new FloatVector.Rel<TemperatureUnit>(value, tempUnit, StorageType.SPARSE);
            FloatVector.Rel<TemperatureUnit> dvCopy = dv;
            MutableFloatVector.Rel<TemperatureUnit> mdv = dv.mutable();
            checkContentsAndType(dv, value, 0.001, tempUnit, false);
            checkContentsAndType(mdv, value, 0.001, tempUnit, false);
            checkContentsAndType(dvCopy, value, 0.001, tempUnit, false);
            MutableFloatVector.Rel<TemperatureUnit> mdvCopy = mdv.copy();
            checkContentsAndType(mdvCopy, value, 0.001, tempUnit, false);
            MutableFloatVector.Rel<TemperatureUnit> mmdv = mdv.mutable();
            checkContentsAndType(mmdv, value, 0.001, tempUnit, false);
            assertEquals("hashCode is independent on mutability", dv.hashCode(), mdv.hashCode());
            // Modify mdv
            mdv.setInUnit(0, 12345, TemperatureUnit.DEGREE_CELSIUS);
            checkContentsAndType(dv, value, 0.001, tempUnit, false);
            checkContentsAndType(mdv, value2, 0.01, tempUnit, false);
            checkContentsAndType(mdvCopy, value, 0.001, tempUnit, false);
            checkContentsAndType(mmdv, value, 0.001, tempUnit, false);
            FloatVector.Rel<TemperatureUnit> idv = mdv.immutable();
            assertTrue("Different value extremely likely results in different hashCode", dv.hashCode() != mdv
                .hashCode());
            // Restore value of mdv
            mdv.setSI(0, dv.getSI(0));
            checkContentsAndType(idv, value2, 0.01, tempUnit, false);
            checkContentsAndType(mdv, value, 0.001, tempUnit, false);
            checkContentsAndType(mmdv, value, 0.001, tempUnit, false);
            mmdv.setSI(0, 0);
            checkContentsAndType(mdv, value, 0.001, tempUnit, false);
            assertEquals("value should be about -273", -273, mmdv.getInUnit(0, tempUnit), 0.2);
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected exception: " + ve.toString());
        }
    }

    /**
     * Test the equals method.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void equalsRelTest()
    {
        LengthUnit lengthUnit = LengthUnit.METER;
        float value = 38.0f;
        FloatScalar.Rel<LengthUnit> dv = new FloatScalar.Rel<LengthUnit>(value, lengthUnit);
        assertTrue("Equal to itself", dv.equals(dv));
        assertFalse("Not equal to null", dv.equals(null));
        assertFalse("Not equal to some other kind of object; e.g. a String", dv.equals(new String("abc")));
        FloatScalar.Abs<LengthUnit> dvCounterPart = new FloatScalar.Abs<LengthUnit>(value, lengthUnit);
        assertFalse("Not equal if one Absolute and other Relative", dv.equals(dvCounterPart));
        FloatScalar.Rel<TemperatureUnit> dvWrongBaseUnit =
            new FloatScalar.Rel<TemperatureUnit>(value, TemperatureUnit.KELVIN);
        assertEquals("The underlying SI values are the same", dv.getSI(), dvWrongBaseUnit.getSI(), 0.0001);
        assertFalse("Not equals because the standard SI unit differs", dv.equals(dvWrongBaseUnit));
        FloatScalar.Rel<LengthUnit> dvCompatibleUnit = new FloatScalar.Rel<LengthUnit>(38000.0f, LengthUnit.MILLIMETER);
        assertFalse("Units are different", dv.getUnit().equals(dvCompatibleUnit.getUnit()));
        assertTrue("equals returns true", dv.equals(dvCompatibleUnit));
        FloatScalar.Rel<LengthUnit> dvDifferentValue = new FloatScalar.Rel<LengthUnit>(123.456f, LengthUnit.MILLIMETER);
        assertFalse("Different value makes equals return false", dv.equals(dvDifferentValue));
    }

    /**
     * Test the Math functions.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void mathFunctionsTestRelTest()
    {
        float[] seedValues = {-10f, -2f, -1f, -0.5f, -0.1f, 0f, 0.1f, 0.5f, 1f, 2f, 10f};
        for (float seedValue : seedValues)
        {
            float[] input = data(3, seedValue);
            MutableFloatVector.Rel<LengthUnit> dv;
            try
            {
                dv = new MutableFloatVector.Rel<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.abs();
                MathTester.tester(input, "abs", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return Math.abs(d);
                    }
                });
                dv = new MutableFloatVector.Rel<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.ceil();
                MathTester.tester(input, "ceil", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return (float) Math.ceil(d);
                    }
                });
                dv = new MutableFloatVector.Rel<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.floor();
                MathTester.tester(input, "floor", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return (float) Math.floor(d);
                    }
                });
                dv = new MutableFloatVector.Rel<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.rint();
                MathTester.tester(input, "rint", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return (float) Math.rint(d);
                    }
                });
                dv = new MutableFloatVector.Rel<LengthUnit>(input, LengthUnit.METER, StorageType.SPARSE);
                dv.round();
                MathTester.tester(input, "round", dv, 0.001, new FloatToFloat()
                {
                    @Override
                    public float function(final float d)
                    {
                        return Math.round(d);
                    }
                });
            }
            catch (ValueException ve)
            {
                fail("Caught unexpected ValueException: " + ve.toString());
            }
        }
    }

    /**
     * Test plus(FloatVectorRel.Sparse, FloatVectorRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfRelSparseAndRelDenseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Rel<LengthUnit> left =
                new FloatVector.Rel<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Rel<?> result = left.plus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI plus of contributing elements", left.getSI(i)
                    + right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(FloatVectorRel.Sparse, FloatVectorRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfRelSparseAndRelDenseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Rel<LengthUnit> left =
                new FloatVector.Rel<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Rel<?> result = left.minus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI minus of contributing elements", left.getSI(i)
                    - right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test times(FloatVectorRel.Sparse, FloatVectorRel.Dense).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binarytimesOfRelSparseAndRelDenseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Rel<LengthUnit> left =
                new FloatVector.Rel<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Rel<?> result = left.times(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI times of contributing elements", left.getSI(i)
                    * right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test plus(FloatVectorRel.Sparse, FloatVectorRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryplusOfRelSparseAndRelSparseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Rel<LengthUnit> left =
                new FloatVector.Rel<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Rel<?> result = left.plus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI plus of contributing elements", left.getSI(i)
                    + right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test minus(FloatVectorRel.Sparse, FloatVectorRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binaryminusOfRelSparseAndRelSparseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Rel<LengthUnit> left =
                new FloatVector.Rel<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Rel<?> result = left.minus(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI minus of contributing elements", left.getSI(i)
                    - right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test times(FloatVectorRel.Sparse, FloatVectorRel.Sparse).
     */
    @SuppressWarnings("static-method")
    @Test
    public final void binarytimesOfRelSparseAndRelSparseTest()
    {
        try
        {
            float[] leftValue = data(3, 123.4f);
            float[] rightValue = data(3, 234.5f);
            FloatVector.Rel<LengthUnit> left =
                new FloatVector.Rel<LengthUnit>(leftValue, LengthUnit.MILE, StorageType.SPARSE);
            FloatVector.Rel<LengthUnit> right =
                new FloatVector.Rel<LengthUnit>(rightValue, LengthUnit.MILE, StorageType.DENSE);
            FloatVector.Rel<?> result = left.times(right);
            for (int i = 0; i < leftValue.length; i++)
            {
                assertEquals("value of element should be SI times of contributing elements", left.getSI(i)
                    * right.getSI(i), result.getSI(i), 0.001);
            }
        }
        catch (ValueException ve)
        {
            fail("Caught unexpected ValueException: " + ve.toString());
        }
    }

    /**
     * Test that malformed or mismatching arrays throw a ValueException.
     */
    @SuppressWarnings("static-method")
    @Test
    public final void sizeCheckRelTest()
    {
        int junk = 0;
        try
        {
            // null array
            new FloatVector.Rel<TemperatureUnit>((float[]) null, TemperatureUnit.DEGREE_FAHRENHEIT, StorageType.SPARSE);
            fail("Preceding code should have thrown a ValueException");
        }
        catch (ValueException ve)
        {
            // Ignore (exception was expected)
            junk++;
        }
        assertTrue("The variable junk is only used to suppress annoying warnings of the code checker", junk > 0);
    }

    /** */
    interface FloatToFloat
    {
        /**
         * @param d float; value
         * @return float value
         */
        float function(float d);
    }

    /** */
    abstract static class MathTester
    {
        /**
         * Test a math function.
         * @param inputValues float[]; unprocessed value
         * @param operation String; description of method that is being tested
         * @param actualResult FloatVector&lt;?&gt;; the actual result of the operation
         * @param precision double; expected accuracy
         * @param function FloatToFloat; encapsulated function that converts one inputValue to an outputValue
         */
        public static void tester(final float[] inputValues, final String operation, final AbstractFloatVector<?, ?> actualResult,
            final double precision, final FloatToFloat function)
        {
            for (int i = 0; i < inputValues.length; i++)
            {
                float expectedResult = function.function(inputValues[i]);
                float got = 0;
                try
                {
                    got = actualResult.getSI(i);
                }
                catch (ValueException ve)
                {
                    fail("Caught unexpected exception: " + ve.toString());
                }
                String description =
                    String.format("%s(%f->%f should be equal to %f with precision %f", operation, inputValues[i],
                        expectedResult, got, precision);
                // System.out.println(description);
                assertEquals(description, expectedResult, got, precision);
            }
        }

    }

}
